export const DOCUMENT_CATEGORIES = [
  "All categories",
  "Land law",
  "Policy",
  "Surveying",
  "Land administration",
  "Land-use planning",
  "Environment",
  "Forestry",
  "Water resources",
  "Institutional reports",
] as const;

export type DocumentCategory = Exclude<(typeof DOCUMENT_CATEGORIES)[number], "All categories">;

export type OfficialDocument = {
  id: string;
  title: string;
  issuer: string;
  year: number;
  category: DocumentCategory;
  language: string;
  description: string;
  tags: string[];
  pdfUrl: string;
  sourceUrl: string;
  legalInstrument?: boolean;
  featured?: boolean;
};

const nla = "National Land Authority";
const nlaLaws = "https://www.lands.rw/publications/laws";
const nlaOther = "https://www.lands.rw/publications/other-documents";
const nlaReports = "https://www.lands.rw/publications/reports";
const nlaPlanning = "https://www.lands.rw/land-use-and-mapping";

export const OFFICIAL_DOCUMENTS: OfficialDocument[] = [
  {
    id: "national-land-policy-2019",
    title: "Revised National Land Policy",
    issuer: nla,
    year: 2019,
    category: "Policy",
    language: "English",
    description: "National policy direction for secure tenure, efficient land administration and sustainable land management.",
    tags: ["land policy", "tenure", "administration", "governance"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Policies/Revised_National_Land_Policy-Final_Version_2019.pdf",
    sourceUrl: "https://www.lands.rw/publications/policies",
    featured: true,
  },
  {
    id: "law-governing-land-2021",
    title: "Law No. 27/2021 Governing Land",
    issuer: nla,
    year: 2021,
    category: "Land law",
    language: "Kinyarwanda / English / French",
    description: "Official Gazette publication of Rwanda's land law, including rights, registration, use and land administration provisions.",
    tags: ["land law", "rights", "registration", "tenure", "disputes"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Laws/Official_Gazette_n___Special_of_10.06.2021_Itegeko_rigenga_ubutaka.pdf",
    sourceUrl: nlaLaws,
    legalInstrument: true,
    featured: true,
  },
  {
    id: "expropriation-law-2015",
    title: "Law No. 32/2015 Relating to Expropriation in the Public Interest",
    issuer: nla,
    year: 2015,
    category: "Land law",
    language: "Kinyarwanda / English / French",
    description: "Official Gazette instrument governing expropriation in the public interest and related compensation procedures.",
    tags: ["expropriation", "compensation", "public interest", "valuation"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Laws/Expropriation_Law_Official_Gazette_of_31.08.2015.pdf",
    sourceUrl: nlaLaws,
    legalInstrument: true,
  },
  {
    id: "valuation-profession-law-2010",
    title: "Law No. 17/2010 Establishing the Real Property Valuation Profession",
    issuer: nla,
    year: 2010,
    category: "Land law",
    language: "Kinyarwanda / English / French",
    description: "Official Gazette instrument establishing and organising the real-property valuation profession in Rwanda.",
    tags: ["valuation", "real property", "valuer", "profession"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Laws/Valuation_law_Gazetted_on_17.05.2010.pdf",
    sourceUrl: nlaLaws,
    legalInstrument: true,
  },
  {
    id: "environment-law-2018",
    title: "Law No. 48/2018 on Environment",
    issuer: nla,
    year: 2018,
    category: "Land law",
    language: "Kinyarwanda / English / French",
    description: "Official environmental law relevant to land-use screening, protected areas, wetlands and environmental management.",
    tags: ["environment", "wetlands", "protection", "land use"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Laws/Law_on_environment.pdf",
    sourceUrl: nlaLaws,
    legalInstrument: true,
  },
  {
    id: "roads-law-2011",
    title: "Law No. 55/2011 Governing Roads in Rwanda",
    issuer: nla,
    year: 2011,
    category: "Land law",
    language: "Kinyarwanda / English / French",
    description: "Official Gazette law governing road classifications, management and road-related land considerations.",
    tags: ["roads", "right of way", "transport", "buffer"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Laws/LAW_GOVERNING_ROADS_IN_RWANDA.pdf",
    sourceUrl: nlaLaws,
    legalInstrument: true,
  },
  {
    id: "condominium-law-2010",
    title: "Law No. 15/2010 Creating and Organising Condominiums",
    issuer: nla,
    year: 2010,
    category: "Land law",
    language: "Kinyarwanda / English / French",
    description: "Official Gazette instrument establishing condominiums and procedures for their registration.",
    tags: ["condominium", "registration", "property", "units"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Laws/Condominium_Law_gazetted_on_14.05.2010.pdf",
    sourceUrl: nlaLaws,
    legalInstrument: true,
  },
  {
    id: "abandoned-property-law-2015",
    title: "Law No. 39/2015 Relating to the Management of Abandoned Property",
    issuer: nla,
    year: 2015,
    category: "Land law",
    language: "Kinyarwanda / English / French",
    description: "Official Gazette instrument addressing identification, administration and management of abandoned property.",
    tags: ["abandoned property", "management", "property rights"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Laws/Abandoned_property_Law_n___39_of_2015.pdf",
    sourceUrl: nlaLaws,
    legalInstrument: true,
  },
  {
    id: "notary-law-2014",
    title: "Law No. 13bis/2014 Governing the Office of Notary",
    issuer: nla,
    year: 2014,
    category: "Land law",
    language: "Kinyarwanda / English / French",
    description: "Official Gazette law governing notarial functions relevant to authenticated land transactions.",
    tags: ["notary", "land transaction", "authentication"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Laws/LOI_NOTAIRE.pdf",
    sourceUrl: nlaLaws,
    legalInstrument: true,
  },
  {
    id: "civil-commercial-procedure-law-2018",
    title: "Law No. 22/2018 Relating to Civil, Commercial, Labour and Administrative Procedure",
    issuer: nla,
    year: 2018,
    category: "Land law",
    language: "Kinyarwanda / English / French",
    description: "Procedure law published by NLA as a related legal reference for administrative and property matters.",
    tags: ["procedure", "civil", "commercial", "administrative"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Laws/Law_N___22_2018_of_29_04_2018_relating_to_the_Civil__Commercial__Labour_and_Administrative_Procedure.pdf",
    sourceUrl: nlaLaws,
    legalInstrument: true,
  },
  {
    id: "cadastral-surveying-manual-2025",
    title: "Cadastral Surveying Procedure Manual",
    issuer: nla,
    year: 2025,
    category: "Surveying",
    language: "English",
    description: "Current NLA technical manual covering Rwanda's spatial reference framework, measurement standards and cadastral surveying workflow.",
    tags: ["cadastral", "surveying", "GNSS", "CORS", "subdivision", "boundaries"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Other_Documents/CADASRAL_SURVEYINGPROCEDURE_MANUAL_22.pdf",
    sourceUrl: nlaOther,
    featured: true,
  },
  {
    id: "certified-surveyors-2026",
    title: "Certified Surveyors and Licensed Companies - 2026",
    issuer: nla,
    year: 2026,
    category: "Surveying",
    language: "English",
    description: "NLA-published list of people and companies certified to practise land surveying for the stated year.",
    tags: ["certified surveyors", "licensed companies", "registry", "2026"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Other_Documents/Certified_surveyors_and_Licensed_Companies_for_practicing_land_surveying_profession__for_Year_2026.pdf",
    sourceUrl: nlaOther,
    featured: true,
  },
  {
    id: "private-land-notaries-2025",
    title: "Private Land Notaries - Final List, October 2025",
    issuer: nla,
    year: 2025,
    category: "Land administration",
    language: "Kinyarwanda",
    description: "Official NLA list of authorised private notaries working in land-related services as published in October 2025.",
    tags: ["notaries", "land services", "authorised practitioners"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Other_Documents/urutonde_rw_abanoteri_-_October_2025.PDF",
    sourceUrl: nlaOther,
  },
  {
    id: "planning-professionals-2025",
    title: "Authorised Urban and Rural Planning Professionals - July 2025",
    issuer: nla,
    year: 2025,
    category: "Land-use planning",
    language: "Kinyarwanda",
    description: "NLA list of professionals authorised to practise urban and rural land-use planning for the stated publication period.",
    tags: ["urban planning", "rural planning", "professionals", "authorised"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Other_Documents/RUPI.pdf",
    sourceUrl: nlaOther,
  },
  {
    id: "private-land-notary-instructions-2025",
    title: "Instructions Governing Private Land Notaries",
    issuer: nla,
    year: 2025,
    category: "Land administration",
    language: "Kinyarwanda",
    description: "NLA instructions governing private notarial practice for land services, published in February 2025.",
    tags: ["notary", "instructions", "land transaction", "practice"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Other_Documents/AMABWIRIZA_NOTERI_WIKORERA_2025.pdf",
    sourceUrl: nlaOther,
  },
  {
    id: "land-reference-prices-2021",
    title: "Rwanda Land Reference Prices 2021",
    issuer: "Institute of Real Property Valuers in Rwanda / NLA",
    year: 2021,
    category: "Land administration",
    language: "Kinyarwanda / English / French",
    description: "Official Gazette publication of reference land prices prepared by the Institute of Real Property Valuers in Rwanda.",
    tags: ["land prices", "valuation", "district", "reference prices"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Other_Documents/Ibiciro_fatizo_by_ubutaka_-_2021.pdf",
    sourceUrl: nlaOther,
    legalInstrument: true,
    featured: true,
  },
  {
    id: "nla-structure-2024",
    title: "National Land Authority Organisational Structure",
    issuer: nla,
    year: 2024,
    category: "Institutional reports",
    language: "English",
    description: "Published overview of the National Land Authority's organisational structure.",
    tags: ["NLA", "organisation", "structure", "institution"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Other_Documents/NLA_Structure_-_Feb_2024.pdf",
    sourceUrl: nlaOther,
  },
  {
    id: "land-dispute-manual-2023",
    title: "Land Dispute Resolution Procedure Manual",
    issuer: nla,
    year: 2023,
    category: "Land administration",
    language: "Kinyarwanda",
    description: "NLA procedure manual for handling land-boundary and systematic-registration disputes.",
    tags: ["land dispute", "boundary", "appeal", "mediation", "procedure"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Other_Documents/Land_dispute_resolution_Procedure_manual_-_Kinyarwanda.pdf",
    sourceUrl: nlaOther,
    featured: true,
  },
  {
    id: "client-charter-2023",
    title: "National Land Authority Client Charter",
    issuer: nla,
    year: 2023,
    category: "Land administration",
    language: "Kinyarwanda",
    description: "NLA client-service charter outlining service commitments and public-facing administrative information.",
    tags: ["client charter", "services", "service standards", "public"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Other_Documents/Client_charter_-_Kinyarwanda_-_Ugushyingo_2023.pdf",
    sourceUrl: nlaOther,
  },
  {
    id: "nla-annual-report-2024-2025",
    title: "NLA Annual Activity Report 2024-2025",
    issuer: nla,
    year: 2025,
    category: "Institutional reports",
    language: "English",
    description: "National Land Authority report on activities, delivery and institutional performance for fiscal year 2024-2025.",
    tags: ["annual report", "performance", "activities", "NLA"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Reports/NLA_Annual_activity_Report_2024-2025.pdf",
    sourceUrl: nlaReports,
    featured: true,
  },
  {
    id: "nla-financial-audit-2025",
    title: "NLA Financial Audit Report - Year Ended 30 June 2025",
    issuer: nla,
    year: 2025,
    category: "Institutional reports",
    language: "English",
    description: "Published financial audit report for the National Land Authority for the year ended 30 June 2025.",
    tags: ["financial audit", "accountability", "NLA", "2025"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Reports/NLA_-_Final__Financial_Audit_Report_for_the_year_ended_30_June_2025.pdf",
    sourceUrl: nlaReports,
  },
  {
    id: "national-land-use-master-plan-2020-2050",
    title: "National Land Use and Development Master Plan 2020-2050",
    issuer: "Ministry of Environment / NLA",
    year: 2020,
    category: "Land-use planning",
    language: "English",
    description: "National spatial framework integrating settlement, economy, agriculture, environment, transport, utilities and public services through 2050.",
    tags: ["NLUDMP", "master plan", "spatial planning", "zoning", "2050"],
    pdfUrl: "https://www.environment.gov.rw/fileadmin/user_upload/Moe/Publications/Policies/National_Land-Use_and_Development_Master_Plan_2020-2050.pdf",
    sourceUrl: nlaPlanning,
    legalInstrument: true,
    featured: true,
  },
  {
    id: "land-use-zoning-regulations",
    title: "Land Use Plans Zoning Regulations",
    issuer: nla,
    year: 2023,
    category: "Land-use planning",
    language: "English",
    description: "National guiding tool for applying land-use plan zones, permitted uses, development controls and planning overlays.",
    tags: ["zoning", "permitted use", "development control", "subdivision", "density"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Master_Plans/Land_Use_Plans_Zoning_Regulations/Land_Use_Plans_Zoning_Regulations_-_Guiding_tool_for_the_implementation_of_land_use_plans_in_Rwanda_.pdf",
    sourceUrl: nlaPlanning,
    featured: true,
  },
  {
    id: "national-land-use-planning-guidelines",
    title: "Rwanda National Land Use Planning Guidelines",
    issuer: nla,
    year: 2023,
    category: "Land-use planning",
    language: "English",
    description: "Planning guidance covering plan hierarchies, analysis, densification, zoning, colour coding and implementation considerations.",
    tags: ["planning guidelines", "zoning", "densification", "land use"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Regulations/Guidelines/NLUP_Guidelines_Final_Published.pdf",
    sourceUrl: nlaPlanning,
  },
  {
    id: "musanze-district-land-use-plan-2023-2050",
    title: "Musanze District Land Use Plan 2023-2050",
    issuer: "NLA / Musanze District",
    year: 2025,
    category: "Land-use planning",
    language: "Kinyarwanda / English",
    description: "Gazetted district land-use plan allocating urban and rural land uses in alignment with the national master plan.",
    tags: ["Musanze", "district plan", "DLUP", "zoning"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Master_Plans/District_Land_Use_Plans/Reports/OG_n___Special_of_31.07.2025__MUSANZE_Igishushanyo_mbonera_cy_imikoreshereze_n_imitunganyirize_by_ubutaka.pdf",
    sourceUrl: nlaPlanning,
    legalInstrument: true,
  },
  {
    id: "gisagara-district-land-use-plan-2023-2050",
    title: "Gisagara District Land Use Plan 2023-2050",
    issuer: "NLA / Gisagara District",
    year: 2024,
    category: "Land-use planning",
    language: "Kinyarwanda / English",
    description: "Gazetted district plan and implementation framework for the allocation and management of land uses in Gisagara.",
    tags: ["Gisagara", "district plan", "DLUP", "zoning"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Master_Plans/District_Land_Use_Plans/Reports/OG_n___Special_of_24.9.2024_Akarere_ka_Gisagara_Imikoreshereze_n_imitunganyirize_by_ubutaka.pdf",
    sourceUrl: nlaPlanning,
    legalInstrument: true,
  },
  {
    id: "ngoma-district-land-use-plan-2023-2050",
    title: "Ngoma District Land Use Plan 2023-2050",
    issuer: "NLA / Ngoma District",
    year: 2025,
    category: "Land-use planning",
    language: "Kinyarwanda / English",
    description: "Gazetted district land-use plan with spatial development, zoning and implementation guidance for Ngoma.",
    tags: ["Ngoma", "district plan", "DLUP", "zoning"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Master_Plans/District_Land_Use_Plans/Reports/OG_n___Special_Bis_of_08.08.2025_NGOMA_Igishushanyo_mbonera_cy_imikoreshereze_n_imitunganyirize_by_ubutaka.pdf",
    sourceUrl: nlaPlanning,
    legalInstrument: true,
  },
  {
    id: "bugesera-district-land-use-plan",
    title: "Bugesera District Land Use Plan",
    issuer: "NLA / Bugesera District",
    year: 2024,
    category: "Land-use planning",
    language: "English",
    description: "District land-use planning report aligning settlement, infrastructure, green growth and spatial development with NLUDMP 2020-2050.",
    tags: ["Bugesera", "district plan", "DLUP", "green growth"],
    pdfUrl: "https://www.lands.rw/fileadmin/user_upload/LANDS/Publications/Master_Plans/District_Land_Use_Plans/Reports/Bugesera_DLUP_Draft_Final_Report.pdf",
    sourceUrl: nlaPlanning,
  },
  {
    id: "rwanda-water-resources-master-plan",
    title: "Rwanda National Water Resources Master Plan",
    issuer: "Rwanda Water Resources Board",
    year: 2015,
    category: "Water resources",
    language: "English",
    description: "National catchment-based assessment and planning framework for sustainable water allocation, demand and development.",
    tags: ["water", "catchments", "hydrology", "demand", "IWRM"],
    pdfUrl: "https://www.rwb.rw/fileadmin/user_upload/RWRB/Publications/Policies/Rwanda_National_Water_Resources_Master_Plan.pdf",
    sourceUrl: "https://waterportal.rwb.rw/node/215",
    featured: true,
  },
  {
    id: "rwanda-state-environment-outlook-2021",
    title: "Rwanda State of Environment and Outlook Report 2021",
    issuer: "Rwanda Environment Management Authority",
    year: 2021,
    category: "Environment",
    language: "English",
    description: "National environmental assessment covering land, water, wetlands, biodiversity, climate, settlements and resource trends.",
    tags: ["environment", "atlas", "wetlands", "water", "biodiversity", "land cover"],
    pdfUrl: "https://www.rema.gov.rw/fileadmin/user_upload/REMA/Publications/State_of_Environment___Atlas/Rwanda_State_of_Environment_and_Outlook_Report_2021.pdf",
    sourceUrl: "https://www.rema.gov.rw/resources/publications",
    featured: true,
  },
  {
    id: "national-forestry-policy-2018",
    title: "Rwanda National Forestry Policy 2018",
    issuer: "Ministry of Environment",
    year: 2018,
    category: "Forestry",
    language: "English",
    description: "National policy for sustainable forest management, landscape restoration, climate resilience and forest-sector development.",
    tags: ["forestry", "forest restoration", "agroforestry", "climate resilience"],
    pdfUrl: "https://environment.gov.rw/fileadmin/user_upload/Moe/Publications/Policies/Rwanda_National_Forestry_Policy_2018.pdf",
    sourceUrl: "https://environment.gov.rw/publications",
    featured: true,
  },
  {
    id: "environment-natural-resources-strategy-2018-2024",
    title: "Environment and Natural Resources Sector Strategy 2018-2024",
    issuer: "Ministry of Environment",
    year: 2018,
    category: "Environment",
    language: "English",
    description: "Sector strategy spanning environment, climate, forestry, land, water resources, mining and meteorology.",
    tags: ["environment", "natural resources", "land", "forestry", "water", "strategy"],
    pdfUrl: "https://www.environment.gov.rw/fileadmin/user_upload/Moe/Publications/Strategies/Environment_and_Natural_Resources_Sector_Strategy_2018-2024__1_.pdf",
    sourceUrl: "https://environment.gov.rw/publications",
  },
];

export function searchOfficialDocuments(query: string, category = "All categories") {
  const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  return OFFICIAL_DOCUMENTS.filter((document) => {
    if (category !== "All categories" && document.category !== category) return false;
    if (!terms.length) return true;
    const haystack = [document.title, document.issuer, document.category, document.language, document.description, ...document.tags]
      .join(" ")
      .toLowerCase();
    return terms.every((term) => haystack.includes(term));
  });
}
